apiVersion: csidriver.storage.openshift.io/v1alpha1
kind: CSIDriverDeployment
metadata:
  name: csidriverdeployment-sample
spec:
  driverName: com.google.csi.gcepd

  driverControllerTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image:  gcr.io/google-containers/volume-csi/gcp-compute-persistent-disk-csi-driver:v0.1.0.alpha
        imagePullPolicy: IfNotPresent
        name: gce-driver

  driverPerNodeTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: gcr.io/google-containers/volume-csi/gcp-compute-persistent-disk-csi-driver:v0.1.0.alpha
        imagePullPolicy: IfNotPresent
        name: gce-driver
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-dir
          mountPath: /host/dev
      volumes:
      - name: device-dir
        hostPath:
          path: /dev
          type: Directory

  driverSocket: /csi/csi.sock
  nodeUpdateStrategy: Rolling

  storageClassTemplates:
    - metadata:
        name: sc1
      default: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate

    - metadata:
        name: sc2
      parameters:
        foo1: bar1
