apiVersion: csidriver.storage.openshift.io/v1alpha1
kind: CSIDriverDeployment
metadata:
  name: hostpath
spec:
  driverName: csi-hostpath

  driverControllerTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/hostpathplugin:v0.2.0
        imagePullPolicy: IfNotPresent
        name: csi-driver
        volumeMounts:
        - name: hostpath-root
          mountPath: /tmp
        securityContext:
          privileged: true
      volumes:
      - name: hostpath-root
        hostPath:
          path: /tmp
          type: Directory

  driverPerNodeTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/hostpathplugin:v0.2.0
        imagePullPolicy: IfNotPresent
        name: csi-driver
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/origin/openshift.local.volumes/pods/
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - name: device-dir
          mountPath: /host/dev
        - name: hostpath-root
          mountPath: /tmp
      volumes:
      - hostPath:
          path: /var/lib/origin/openshift.local.volumes/pods/
        type: DirectoryOrCreate
        name: mountpoint-dir
      - name: hostpath-root
        hostPath:
          path: /tmp
          type: Directory
      - name: device-dir
        hostPath:
          path: /dev
          type: Directory

  driverSocket: /csi/csi.sock
  nodeUpdateStrategy: Rolling

  storageClassTemplates:
    - metadata:
        name: sc1
      default: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      
    - metadata:
        name: sc2
      parameters:
        foo1: bar1
