apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:csi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:operator:csi-operator
subjects:
- kind: ServiceAccount
  name: csi-operator
  namespace: openshift-csi-operator

---

# A service account needs to have the privileges it's going to give to
# other service accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:csi-operator-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:csi-driver
subjects:
- kind: ServiceAccount
  name: csi-operator
  namespace: openshift-csi-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:csi-operator-self-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:csi-driver-controller-leader-election
subjects:
- kind: ServiceAccount
  name: csi-operator
  namespace: openshift-csi-operator
