apiVersion: csidriver.storage.openshift.io/v1alpha1
kind: CSIDriverDeployment
metadata:
  name: csidriverdeployment-sample
spec:
  driverName: ebs.csi.aws.com

  driverControllerTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: access_key
        image:  amazon/aws-ebs-csi-driver:0.1.0-alpha
        imagePullPolicy: IfNotPresent
        name: ebs-driver

  driverPerNodeTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: access_key
        image:  amazon/aws-ebs-csi-driver:0.1.0-alpha
        imagePullPolicy: IfNotPresent
        name: ebs-driver
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-dir
          mountPath: /host/dev
      volumes:
      - name: device-dir
        hostPath:
          path: /dev
          type: Directory

  driverSocket: /csi/csi.sock
  nodeUpdateStrategy: Rolling

  storageClassTemplates:
    - metadata:
        name: sc1
      default: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
