apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-operator
  namespace: csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-operator
  template:
    metadata:
      labels:
        name: csi-operator
    spec:
      serviceAccount: csi-operator
      containers:
        - name: csi-operator
          image: csi-operator:canary
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "csi-operator"
