apiVersion: csidriver.storage.okd.io/v1alpha1
kind: CSIDriverDeployment
metadata:
  name: csidriverdeployment-sample
spec:
  driverName: mock

  driverControllerTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: /csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/mock-driver:v0.2.0
        imagePullPolicy: IfNotPresent
        name: mock-driver
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
        type: DirectoryOrCreate
        name: mountpoint-dir

  driverPerNodeTemplate:
    spec:
      containers:
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        env:
        - name: CSI_ENDPOINT
          value: /csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/mock-driver:v0.2.0
        imagePullPolicy: IfNotPresent
        name: mock-driver
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir

  driverSocket: /csi/csi.sock
  nodeUpdateStrategy: Rolling

  storageClassTemplates:
    - metadata:
        name: sc1
      default: true
      parameters:
        foo: bar
      reclaimPolicy: Delete
      mountOptions:
        - foo
        - bar
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      
    - metadata:
        name: sc2
      parameters:
        foo1: bar1
