# Default images to use for various external Kubernetes components.
defaultImages:
  attacherImage: "quay.io/k8scsi/csi-attacher:v0.3.0"
  provisionerImage: "quay.io/k8scsi/csi-provisioner:v0.3.1"
  driverRegistrarImage: "quay.io/k8scsi/driver-registrar:v0.3.0"
  livenessProbeImage: "quay.io/k8scsi/livenessprobe:latest"

# Label selector that matches nodes where pods with controller components
# (provisioner, attacher) are allowed to run. These pods typically have some
# privileged access to the storage backend to attach/detach and create/delete
# volumes and some deployments require such pods to run on dedicated nodes,
# so a node compromised by an user does not have a pod that has credentials
# to the storage backend.
infrastructureNodeSelector:
  # Empty by default, run anywhere

# Number of replicas of controller pods (provisioner, attacher).
# (Leader election is not supported now).
deploymentReplicas: 1

# Name of ClusterRole that gives CSI driver pods and Kubernetes sidecar
# container enough permissions to run.
clusterRoleName: csidriver

# Name of ClusterRole that gives CSI external attacher and provisioner
# permissions to do leader election in its namespace.
leaderElectionClusterRoleName: csidriver-controller-leader-election

# Root of kubelet data directory on all nodes.
kubeletRootDir: /var/lib/kubelet
